modulo_ventas/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('NOSOTROS/', views.nosotros, name='nosotros'),
    path('accounts/profile/', views.profile, name='profile'),  # Ruta para el perfil
    path('realizar_pedido/', views.realizar_pedido, name='realizar_pedido'),
    path('ver_estatus_pedido/', views.ver_estatus_pedido, name='ver_estatus_pedido'),
    path('pedido/<int:pedido_id>/', views.detalle_pedido, name='detalle_pedido'),
    path('accounts/profile/ajustes/', views.perfil_empleado, name='perfil_empleado'),
    path('obtener_datos_cliente/', views.obtener_datos_cliente, name='obtener_datos_cliente'),
    path('ticket_it/', views.ticket, name='realizar_ticket'),
    path('ver_ticket/', views.ver_ticket, name='ver_estatus_ticket'),
    path('resolver_ticket/', views.admin_it, name='cerrar_ticket'),
    path('ticket/<int:ticket_id>/', views.detalle_ticket_it, name='detalle_ticket'),
    path('ticket/<int:ticket_id>/cambiar_estado/', views.cambiar_estado_ticket, name='cambiar_estado_ticket'),
    path('directorios/', views.directorio, name='directorios'),
    path('sistemas_directorio/', views.sistemas_dir, name='sistemas_dir'),
    path('administracion_dir/', views.administracion_dir, name= 'administracion_dir'),
    path('cobranza_dir/', views.cobranza_dir, name='cobranza_dir'),
    path('asistente_dir/', views.asistente_dir, name='asistente_dir'),
    path('compras_dir/', views.compras_dir, name='compras_dir'),
    path('produccion_dir/', views.produccion_dir, name='produccion_dir'),
    path('ventas_dir/', views.ventas_dir, name='ventas_dir'),
    path('rh_dir/', views.rh_dir, name='rh_dir'),
    path('formulaciones_dir/', views.formulaciones_dir, name='formulaciones_dir'),
    path('imagen_dir/', views.imagen_dir, name='imagen_dir'),
    path('community_dir/', views.community_dir, name='community_dir'),
    path('recepcion_dir/', views.recepcion_dir, name='recepcion_dir'),
    path('calidad_dir/', views.calidad_dir, name='calidad_dir'),
    path('proyectos_dir/', views.proyectos_dir, name='proyectos_dir'),
    path('ceo_dir/', views.ceo_dir, name='ceo_dir'),
    path('blb_dir/', views.blb_dir, name='blb_dir'),
    path('cambiar-contrasenia/', views.cambiar_contrasenia, name='cambiar_contrasenia'),
    path('cambiar-email/', views.cambiar_email, name='cambiar_email'),
    path('buscar-por-folio/', views.buscar_por_folio, name='buscar_por_folio'),
    path('subir/', views.subir_documento, name='subir_documento'),
    path('documentos/', views.lista_documentos, name='lista_documentos'),
    #path('pedidos-de-facturacion/', views.pedidos_almacen, name='pedido_facturacion'),
    path('almacen/facturas/', views.pedidos_almacen, name='pedidos_almacen'),
    path('almacen/facturas/<int:factura_id>/', views.detalle_factura, name='detalle_factura'),
    path('almacen/facturacion_estatus/<int:factura_id>/', views.detalle_factura_final, name='detalle_factura_final'),
    path('almacen/facturacion_estatus/', views.facturacion_final, name='facturacion_final'),
    path('almacen/todas_las_facturas_/', views.todas_facturas, name='todas_facturas'),
    path('backorders/', views.backorders_view, name='backorders'),
    path('backorders_detalle/', views.lista_backorders, name='backorders_detalle'),
    path('backorders/<int:backorder_id>/', views.detalle_backorders_almacen, name='detalle_backorder_almacen'),
    path('backorders/estatus/<int:backorder_id>/', views.detalle_backorders_facturacion, name='detalle_backorder_facturacion'),
    path('backorders/enviados/', views.backorders_final, name='guardar_backorder'),
    path('backorders/todos_los_backorders/', views.todos_backorders, name='todos_backorders'),
]

ventas/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from modulo_ventas import views


handler404 = views.vista_404 
handler403 = views.vista_403 

urlpatterns = [
    path('DISTRIBUIDORABLB/', include('modulo_ventas.urls')),
    path('', RedirectView.as_view(url='/DISTRIBUIDORABLB/', permanent=True)),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

modulo_ventas/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Client(models.Model):
    """
    Modelo Client
    Representa la información de un cliente en el sistema de ventas.
    Atributos:
        clave_cliente (BigIntegerField): Clave única del cliente.
        nombre_cliente (CharField): Nombre del cliente.
        rfc (CharField): RFC del cliente.
        calle (CharField): Calle de la dirección del cliente.
        numint (CharField): Número interior de la dirección.
        numext (CharField): Número exterior de la dirección.
        colonia (CharField): Colonia de la dirección.
        codigo (CharField): Código postal.
        municipio (CharField): Municipio de la dirección.
        estado (CharField): Estado de la dirección.
        pais (CharField): País de la dirección.
        telefono (CharField): Número de teléfono del cliente.
        clasificacion (CharField): Clasificación del cliente (FORANEO o LOCAL).
        curp (CharField): CURP del cliente.
        email (EmailField): Correo electrónico del cliente.
    Métodos:
        __str__(): Retorna el nombre del cliente como representación en texto.
    Meta:
        verbose_name: Nombre singular para el modelo en el admin de Django.
        verbose_name_plural: Nombre plural para el modelo en el admin de Django.
        ordering: Ordena los clientes por nombre_cliente.
    """
    
    CLASIF_CHOICES = [
        ('FORANEO', 'FORANEO'),
        ('LOCAL', 'LOCAL'),
    ]
    
    clave_cliente = models.BigIntegerField(unique=True)
    nombre_cliente = models.CharField(verbose_name='Nombre de cliente' ,max_length=255, null=True, blank=True)
    rfc = models.CharField(verbose_name='rfc de cliente',max_length=255, null=True, blank=True)
    calle = models.CharField(verbose_name='calle',max_length=255, null=True, blank=True)
    numint = models.CharField(verbose_name='numero interior', max_length=255, null=True, blank=True)
    numext = models.CharField(verbose_name='numero exterior' ,max_length=255, null=True, blank=True)
    colonia = models.CharField(verbose_name='Nombre de colonia',max_length=255, null=True, blank=True)
    codigo = models.CharField(verbose_name='codigo postal' ,null=True, blank=True, max_length=5)
    municipio = models.CharField(verbose_name='nombre de municipio', max_length=255, null=True, blank=True)
    estado = models.CharField(verbose_name='nombre de estado', max_length=255, null=True, blank=True)
    pais = models.CharField(verbose_name='nombre pais' ,max_length=255, blank=True, null=True)
    telefono = models.CharField(verbose_name='numero de telefono' ,max_length=255, blank=True, null=True)
    clasificacion = models.CharField(
        max_length=20,
        choices=CLASIF_CHOICES,
        null=True,
        blank=True,
    ) 
    curp = models.CharField(verbose_name='curp de cliente' ,max_length=18, null=True, blank= True)
    email = models.EmailField(verbose_name='email cliente' ,max_length=255, null=True, blank=True)   
    
    def __str__(self):
        return self.nombre_cliente  
    
    class Meta:
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'
        ordering = ['nombre_cliente']

class Pedido(models.Model):
    """
    Modelo Pedido representa una orden de venta realizada por un vendedor.
    Atributos:
        nombre_cliente (ForeignKey): Referencia al cliente que realiza el pedido (modelo Client).
        numero_cliente (IntegerField): Número identificador del cliente (opcional).
        nombre_contacto (CharField): Nombre de la persona de contacto para el pedido (opcional).
        fecha_creacion (DateTimeField): Fecha y hora en que se creó el pedido (asignado automáticamente).
        calle (CharField): Calle de la dirección de entrega (opcional).
        colonia (CharField): Colonia de la dirección de entrega (opcional).
        municipio (CharField): Municipio de la dirección de entrega (opcional).
        estado (CharField): Estado de la dirección de entrega (opcional).
        codigo_postal (CharField): Código postal de la dirección de entrega (opcional).
        telefono (CharField): Teléfono de contacto para el pedido (opcional).
        lista_items (IntegerField): Número de listas de items en el pedido (valores posibles: 1, 2, 3).
        estatus (CharField): Estado actual del pedido ('pendiente', 'en_proceso', 'enviado').
        vendedor (ForeignKey): Usuario vendedor asociado al pedido (opcional).
    Métodos:
        __str__(): Retorna una representación legible del pedido, mostrando el cliente y el estatus.
    """
    
    ESTATUS_CHOICES = [
        ('pendiente', 'Pendiente'),
        ('en_proceso', 'En Proceso'),
        ('enviado', 'Enviado'),
    ]

    nombre_cliente = models.ForeignKey(Client, on_delete=models.CASCADE)
    numero_cliente = models.IntegerField(default=0, null=True, blank=True)
    nombre_contacto = models.CharField(max_length=255, null=True, blank=True)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    calle = models.CharField(max_length=255, null=True, blank=True)
    colonia = models.CharField(max_length=255, null=True, blank=True)
    municipio = models.CharField(max_length=255, null=True, blank=True)
    estado = models.CharField(max_length=255, null=True, blank=True)
    codigo_postal = models.CharField(max_length=10, null=True, blank=True)
    telefono = models.CharField(max_length=20, null=True, blank=True)
    lista_items = models.IntegerField(choices=[(i, str(i)) for i in range(1, 4)], default=1)
    estatus = models.CharField(
        max_length=20,
        choices=ESTATUS_CHOICES,
        default='pendiente'
    )
    vendedor = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    
    def __str__(self):
        return f"Pedido {self.nombre_cliente} - {self.estatus}"
    
class Producto(models.Model):
    """
    Modelo Producto que representa un producto en el sistema de ventas.
    Atributos:
        nombre_producto (CharField): Nombre del producto.
        qty_caja (IntegerField): Cantidad de unidades por caja. Valor por defecto: 0.
        linea (CharField): Línea a la que pertenece el producto. Opciones: 'inbelleza', 'barber', 'platinum', 'none'. Valor por defecto: 'none'.
        precio_1 (FloatField): Primer precio del producto. Valor por defecto: 0.
        precio_2 (FloatField): Segundo precio del producto. Valor por defecto: 0.
        precio_3 (FloatField): Tercer precio del producto. Valor por defecto: 0.
        imagen (CharField): Ruta o nombre de la imagen asociada al producto. Puede ser nulo o estar en blanco.
    Métodos:
        __str__(): Retorna el nombre del producto como representación en cadena del objeto.
    """
    
    LINEA_CHOICES = [
        ('inbelleza', 'Inbelleza'),
        ('barber', 'Barber'),
        ('platinum', 'Platinum'),
        ('none', 'None')
    ]
    
    nombre_producto = models.CharField(max_length=255)
    qty_caja = models.IntegerField(default=0)
    linea = models.CharField(
        max_length=20,
        choices=LINEA_CHOICES,
        default='none'
    )
    precio_1 = models.FloatField(default=0)
    precio_2 = models.FloatField(default=0)
    precio_3 = models.FloatField(default=0)
    imagen = models.CharField(max_length=255, null=True, blank=True)
    
    def __str__(self):
        return self.nombre_producto
    
class DetallePedido(models.Model):
    """
    Modelo que representa el detalle de un pedido, enlazando un producto específico a un pedido y especificando la cantidad solicitada.
    Atributos:
        pedido (ForeignKey): Referencia al pedido al que pertenece este detalle.
        producto (ForeignKey): Referencia al producto incluido en el detalle.
        cantidad (PositiveIntegerField): Cantidad del producto solicitada en el pedido.
    Métodos:
        calcular_subtotal():
            Calcula el subtotal del detalle del pedido, seleccionando el precio del producto según la lista de precios asociada al pedido.
            Retorna el resultado de multiplicar la cantidad por el precio correspondiente.
        __str__():
            Retorna una representación legible del detalle, mostrando el nombre del producto y la cantidad solicitada.
    """
    
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE, related_name='detalles')
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField(default=1)

    def calcular_subtotal(self):
        """
        Calcula el subtotal de un ítem en el pedido según la lista de precios seleccionada.
        El método determina el precio del producto basado en el valor de 'lista_items' del pedido:
            - Si 'lista_items' es 1, usa 'precio_1' del producto.
            - Si 'lista_items' es 2, usa 'precio_2' del producto.
            - Si 'lista_items' es 3, usa 'precio_3' del producto.
            - Para cualquier otro valor, el precio es 0.
        Retorna:
            float: El subtotal calculado como la cantidad del producto multiplicada por el precio seleccionado.
        """
                
        # Obtener el precio basado en la selección del pedido
        if self.pedido.lista_items == 1:
            precio = self.producto.precio_1
        elif self.pedido.lista_items == 2:
            precio = self.producto.precio_2
        elif self.pedido.lista_items == 3:
            precio = self.producto.precio_3
        else:
            precio = 0
        return self.cantidad * precio

    def __str__(self):
        return f"{self.producto.nombre_producto} x {self.cantidad}" 
    
class CrearTicket(models.Model):
    """
    Modelo CrearTicket para la gestión de tickets de soporte en el sistema de ventas.
    Campos:
        numero_ticket (UUIDField): Identificador único del ticket, generado automáticamente.
        fecha_creacion (DateTimeField): Fecha y hora de creación del ticket.

modulo_ventas/templates/backorders_final.html
{% extends "base_generic.html" %}

{% block content %}
<div class="container mt-4">
    <h2 class="mb-4">
        <i class="fas fa-check-circle text-success me-2"></i>
        Backorders Completados
    </h2>
    
    <div class="card">
        <div class="card-body">
            {% if facturas %}
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead class="table-light">
                        <tr>
                            <th>Folio</th>
                            <th>Factura</th>
                            <th>Cliente</th>
                            <th>Fecha</th>
                            <th>Productos</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for factura in facturas %}
                        <tr>
                            <td>{{ factura.folio }}</td>
                            <td>{{ factura.factura }}</td>
                            <td>
                                <div class="fw-bold">{{ factura.cliente_nombre }}</div>
                                <small class="text-muted">{{ factura.rfc }}</small>
                            </td>
                            <td>{{ factura.fecha_creacion|date:"d/m/Y" }}</td>
                            <td>{{ factura.productos.count }}</td>
                            <td>
                                <a href="{% url 'detalle_backorder_facturacion' factura.id %}" 
                                   class="btn btn-sm btn-outline-primary">
                                   <i class="fas fa-eye"></i> Ver
                                </a>
                                <!-- <a href="#" class="btn btn-sm btn-outline-success">
                                    <i class="fas fa-file-pdf"></i> PDF
                                </a> -->
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            {% else %}
            <div class="text-center py-5">
                <i class="fas fa-inbox fa-4x text-muted mb-4"></i>
                <h5 class="text-muted">No hay backorders completadas</h5>
                <p class="text-muted">Los Bakcorders aparecerán aquí cuando todos sus productos tengan lote y cantidad asignados</p>
            </div>
            {% endif %}
        </div>
    </div>
</div>

<style>
    .table-hover tbody tr:hover {
        background-color: #f8f9fa;
    }
    .text-muted {
        color: #6c757d !important;
    }
</style>
{% endblock %}

modulo_ventas/templates/lista_backorders.html
{% extends "base_generic.html" %}

{% block content %}
<div class="container mt-4">
    <h2 class="mb-4">BackOrders Registrados</h2>

    <!-- Formulario de Búsqueda -->
    <form method="get" class="mb-4">
        <div class="row">
            <div class="col-md-6">
                <input type="text" name="q" class="form-control" placeholder="Buscar por folio o cliente"
                    value="{{ search_query }}">
            </div>
            <div class="col-md-3">
                <input type="date" name="fecha_inicio" class="form-control" value="{{ fecha_inicio }}"
                    placeholder="Desde">
            </div>
            <div class="col-md-3">
                <input type="date" name="fecha_fin" class="form-control" value="{{ fecha_fin }}" placeholder="Hasta">
            </div>
        </div>
        <button type="submit" class="btn btn-primary mt-2">Buscar</button>
    </form>

    <!-- Listado de BackOrders -->
    <div class="list-group">
        {% for backorder in facturas %}
        <a href="{% url 'detalle_backorder_almacen' backorder.id %}" class="list-group-item list-group-item-action">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">{{ backorder.folio }}</h5>
                <small>{{ backorder.fecha_creacion|date:"d/m/Y" }}</small>
            </div>
            <p class="mb-1">{{ backorder.cliente_nombre }}</p>
            
        </a>
        {% empty %}
        <div class="alert alert-info">No se encontraron BackOrders</div>
        {% endfor %}
    </div>
</div>
{% endblock %}

modulo_ventas/templates/subir_documento.html
{% extends "base_generic.html" %}
{% load static %}

{% block content %}
<!-- subir_documento.html -->
<h1>Subir documento</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Subir</button>
</form>
<a href="{% url 'lista_documentos' %}">Ver documentos</a>
{% endblock %}

modulo_ventas/templates/tickets_it.html
{% extends "base_generic.html" %}
{% load static %}

{% block content %}
<link rel="preload" href="{% static 'css/style-it.css' %}" as="style" onload="this.rel='stylesheet'">
<link rel="stylesheet" href="{% static 'css/style-it.css' %}">
<h1 class="title-section-it">Bienvenido personal IT</h1>
<h3 class="name-section-it">Nombre: {{ user.get_full_name }}</h3>

<form method="GET" class="filter-form-it">
    <!-- Campo para buscar por número de ticket -->

    <div class="form-group-it">
        <label for="ticket">Número de Ticket:</label>
        <input type="text" id="ticket" name="ticket" value="{{ numero_ticket_filtro }}"
            placeholder="Buscar por número de ticket">
    </div>

    <!-- Campo para filtrar por fecha de creación -->
    <div class="form-group-it">
        <label for="fecha_creacion">Fecha de Creación (YYYY-MM-DD)</label>
        <input type="date" id="fecha_creacion" name="fecha_creacion" value="{{ fecha_filtro }}">
    </div>

    <!-- Campo para filtrar por estatus -->
    <div class="form-group-it">
        <label for="estado">Estatus</label>
        <select id="estado" name="estado">
            <option value="">Seleccionar estatus</option>
            <option value="abierto" {% if estado_filtro == 'abierto' %}selected{% endif %}>abierto</option>
            <option value="en progreso" {% if estado_filtro == 'en progreso' %}selected{% endif %}>en progreso</option>
            <option value="resuelto" {% if estado_filtro == 'resuelto' %}selected{% endif %}>resuelto</option>
            <option value="cerrado" {% if estado_filtro == 'cerrado' %}selected{% endif %}>cerrado</option>
        </select>
    </div>

    <!-- Botón para enviar el formulario -->
    <button type="submit" class="filter-btn-it">Buscar</button>
</form>

{% if tickets %}
<p class="count-results-it">Resultados encontrados {{ contador }}</p>
    <ul class="ticket-list-it">
        {% for ticket in tickets %}
            <li class="ticket-item-it">
                <strong>Ticket de {{ ticket.nombre_usuario }}</strong><br>
                <strong>Nivel de prioridad:</strong> {{ ticket.nivel_prioridad }}<br>
                <strong>Número de Ticket:</strong> {{ ticket.numero_ticket }}<br>
                <strong>Categoría:</strong> {{ ticket.get_categoria_display }}<br>
                <strong>Descripción:</strong> {{ ticket.descripcion }}<br>
                <strong>Fecha de Creación:</strong> {{ ticket.fecha_creacion }}<br>
                <strong>Estado:</strong> {{ ticket.get_estado_display }}<br>
                <a class="btn-detalle-it" href="{% url 'detalle_ticket' ticket.id %}">Ver Detalle</a>
            </li>
            <hr class="ticket-divider-it">
        {% endfor %}
    </ul>
{% else %}
    <p class="no-tickets-it">No hay tickets realizados.</p>
{% endif %}

<div class="pagination-it">
    <span class="step-links-it">
        {% if tickets.has_previous %}
            <a class="btn-pagination-it" href="?page=1">Primera</a>
            <a class="btn-pagination-it" href="?page={{ tickets.previous_page_number }}">Anterior</a>
        {% endif %}
        
        <span>Página {{ tickets.number }} de {{ tickets.paginator.num_pages }}</span>
        
        {% if tickets.has_next %}
            <a class="btn-pagination-it" href="?page={{ tickets.next_page_number }}">Siguiente</a>
            <a class="btn-pagination-it" href="?page={{ tickets.paginator.num_pages }}">Última</a>
        {% endif %}
    </span>
</div>

{% endblock %}

modulo_ventas/templates/ver_estatus_pedido.html
{% extends "base_generic.html" %}
{% load static %}

{% block content %}
<link rel="preload" href="{% static 'css/styles-detail.css' %}" as="style" onload="this.rel='stylesheet'">
<link rel="stylesheet" href="{% static 'css/styles-detail.css' %}">
<h1 class="pedidos-titulo2">Estatus del Pedido</h1>
<p>Aquí verás el estatus de tu pedido</p>

<!-- Formulario de búsqueda -->
<form method="GET" class="filter-form">
    <div class="form-group">
        <h2 class="pedidos-titulo2">Busca tu pedido</h2>
        <label for="numero_cliente">Número de Cliente:</label>
        <input type="text" id="numero_cliente" name="numero_cliente" value="{{ request.GET.numero_cliente }}"
            placeholder="Buscar por número de cliente">
    </div>
    <div class="form-group">
        <label for="fecha_creacion">Fecha de Creación (YYYY-MM-DD)</label>
        <input type="date" id="fecha_creacion" name="fecha_creacion" value="{{ request.GET.fecha_creacion }}">
    </div>
    <div class="form-group">
        <label for="estatus">Estatus</label>
        <select id="estatus" name="estatus">
            <option value="">Seleccionar estatus</option>
            <option value="Pendiente" {% if request.GET.estatus == 'Pendiente' %}selected{% endif %}>Pendiente</option>
            <option value="en_proceso" {% if request.GET.estatus == 'en_proceso' %}selected{% endif %}>En Proceso</option>
            <option value="Completado" {% if request.GET.estatus == 'Completado' %}selected{% endif %}>Completado</option>
            <option value="Cancelado" {% if request.GET.estatus == 'Cancelado' %}selected{% endif %}>Cancelado</option>
        </select>
    </div>
    <button type="submit" class="filter-btn">Buscar</button>
</form>

<!-- Controles de paginación -->
{% if pedidos %}
<h2 class="pedidos-titulo">Mis Pedidos</h2>
<p class="count_results">Resultados encontrados {{ contador }}</p>
<div class="pagination">
    <span class="step-links">
        {% if pedidos.has_previous %}
            <a class="btn-detalle" href="?page=1">Primera</a>
            <a class="btn-detalle" href="?page={{ pedidos.previous_page_number }}">Anterior</a>
        {% endif %}
        
        <span>Página {{ pedidos.number }} de {{ pedidos.paginator.num_pages }}</span>
        
        {% if pedidos.has_next %}
            <a class="btn-detalle" href="?page={{ pedidos.next_page_number }}">Siguiente</a>
            <a class="btn-detalle" href="?page={{ pedidos.paginator.num_pages }}">Última</a>
        {% endif %}
    </span>
</div>
<!-- Lista de pedidos -->
<div class="pedidos-lista">
    {% for pedido in pedidos %}
    <div class="pedido-item">
        <h3>Pedido de {{ pedido.nombre_cliente }}</h3>
        <p><strong>Número de Cliente:</strong> {{ pedido.numero_cliente }}</p>
        <p><strong>Vendedor:</strong> {{ pedido.vendedor.get_full_name }}</p>
        <p><strong>Fecha:</strong> {{ pedido.fecha_creacion }}</p>
        <p><strong>Dirección:</strong> {{ pedido.calle }}, {{ pedido.colonia }}, {{ pedido.municipio}}, {{ pedido.estado }}</p>
        <p><strong>Teléfono:</strong> {{ pedido.telefono }}</p>
        <p><strong>Estatus:</strong> {{ pedido.get_estatus_display }}</p>
        <a class="btn-detalle" href="{% url 'detalle_pedido' pedido.id %}">Ver Detalle</a>
    </div>
    {% endfor %}
</div>
{% else %}
<p class="no-pedidos">No tienes pedidos realizados.</p>
{% endif %}
<!-- Controles de paginación -->
<div class="pagination">
    <span class="step-links">
        {% if pedidos.has_previous %}
            <a class="btn-detalle" href="?page=1">Primera</a>
            <a class="btn-detalle" href="?page={{ pedidos.previous_page_number }}">Anterior</a>
        {% endif %}
        
        <span>Página {{ pedidos.number }} de {{ pedidos.paginator.num_pages }}</span>
        
        {% if pedidos.has_next %}
            <a class="btn-detalle" href="?page={{ pedidos.next_page_number }}">Siguiente</a>
            <a class="btn-detalle" href="?page={{ pedidos.paginator.num_pages }}">Última</a>
        {% endif %}
    </span>
</div>

{% endblock %}

modulo_ventas/templates/ver_ticket_detalle.html
{% extends "base_generic.html" %}
{% load static %}

{% block content %}
<link rel="preload" href="{% static 'css/style-it-details.css' %}" as="style" onload="this.rel='stylesheet'">
<link rel="stylesheet" href="{% static 'css/style-it-details.css' %}">
{% if it %}
<div class="ticket-detail-container">
    <h1 class="title-section">Ver tickets</h1>
    <h3 class="name-section">Nombre: {{ user.get_full_name }}</h3>

    <h1 class="ticket-title">Detalle del Ticket</h1>

    <div class="ticket-info">
        <p><strong>Número de Ticket:</strong> {{ ticket.numero_ticket }}</p>
        <p><strong>Categoría:</strong> {{ ticket.get_categoria_display }}</p>
        <p><strong>Descripción:</strong> {{ ticket.descripcion }}</p>
        <p><strong>Fecha de Creación:</strong> {{ ticket.fecha_creacion }}</p>
        <p><strong>Estado:</strong> {{ ticket.get_estado_display }}</p>
        <p><strong>Prioridad:</strong> {{ ticket.nivel_prioridad }}</p>
        <p><strong>Usuario:</strong> {{ ticket.nombre_usuario.get_full_name }}</p>
    </div>

    <form method="POST" action="{% url 'cambiar_estado_ticket' ticket.id %}" class="ticket-form">
        {% csrf_token %}
        <button type="submit" class="btn-proceso">MARCAR PARA SIGUIENTE PROCESO</button>
    </form>

    <a href="{% url 'cerrar_ticket' %}" class="btn-volver">Volver a la lista de tickets</a>
</div>
{% else %}
<p class="no-permission">No tienes permisos de administrador.</p>
{% endif %}
{% endblock %}